#!/usr/bin/env node
/**
 * Writes .env.local from the running local Supabase stack.
 *
 * Local Supabase keys are the well-known development defaults, not secrets, but they are
 * regenerated per machine and per port mapping, so they are derived here rather than committed.
 * `.env*` is gitignored.
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const raw = execFileSync('npx', ['supabase', 'status', '-o', 'env'], {
  encoding: 'utf8',
  stdio: ['ignore', 'pipe', 'ignore'],
});

const status = new Map();
for (const line of raw.split('\n')) {
  const match = line.match(/^([A-Z0-9_]+)="(.*)"$/);
  if (match) status.set(match[1], match[2]);
}

const required = ['API_URL', 'ANON_KEY', 'SERVICE_ROLE_KEY', 'DB_URL'];
const missing = required.filter((key) => !status.has(key));
if (missing.length > 0) {
  console.error(`Missing from supabase status: ${missing.join(', ')}`);
  console.error('Is the local stack running? Try: npm run db:start');
  process.exit(1);
}

const contents = [
  '# Generated by scripts/write-env.mjs — do not edit by hand.',
  '# Regenerate with: npm run db:env',
  '',
  `NEXT_PUBLIC_SUPABASE_URL=${status.get('API_URL')}`,
  `NEXT_PUBLIC_SUPABASE_ANON_KEY=${status.get('ANON_KEY')}`,
  '',
  '# Server-only. Bypasses RLS — never import into client code, never use in tests that',
  '# assert isolation (design.md D12).',
  `SUPABASE_SERVICE_ROLE_KEY=${status.get('SERVICE_ROLE_KEY')}`,
  `SUPABASE_DB_URL=${status.get('DB_URL')}`,
  '',
].join('\n');

writeFileSync(new URL('../.env.local', import.meta.url), contents);
console.log('Wrote .env.local');
